# Generated by Django 2.2.5 on 2019-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0015_auto_20190911_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='ip_addr',
            field=models.GenericIPAddressField(db_index=True, default='0.0.0.0'),
        ),
    ]
